{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "resource.default.namespace" . }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.monitoring.interval | default "60s" }}
{{- end }}

