apiVersion: v1
stringData:
  credentials: |-
    [default]
    aws_access_key_id: {{ .Values.aws.accessKeyID | quote | required "setting aws.accessKeyID is required" }}
    aws_secret_access_key: {{ .Values.aws.secretAccessKey | quote | required "setting aws.secretAccessKey is required" }}
    {{- if .Values.aws.region }}
    region: {{ .Values.aws.region | quote }}
    {{- end }}
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-aws-credentials
  namespace: {{ include "resource.default.namespace" . }}
type: Opaque

---

{{ if or (((.Values.crossplane).aws).staticCredentials).accessKeyID (((.Values.crossplane).aws).staticCredentials).secretAccessKey }}
apiVersion: v1
stringData:
  credentials: |-
    [default]
    aws_access_key_id: {{ .Values.crossplane.aws.staticCredentials.accessKeyID | required "crossplane.aws.staticCredentials.accessKeyID must be given if any static credentials are filled" | quote }}
    aws_secret_access_key: {{ .Values.crossplane.aws.staticCredentials.secretAccessKey | required "crossplane.aws.staticCredentials.secretAccessKey must be given if any static credentials are filled" | quote }}
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: crossplane-aws-credentials
  namespace: crossplane
type: Opaque
{{ end }}
