apiVersion: v2
name: aws-resolver-rules-operator
description: Operator for reconciling the Route53 hosted zone and basic records for a cluster, and resolver rules for private clusters.
home: https://github.com/giantswarm/aws-resolver-rules-operator
icon: https://s.giantswarm.io/app-icons/aws/2/dark.svg
version: "0.25.2"
appVersion: "0.25.2"
annotations:
  io.giantswarm.application.team: "phoenix"
